### ISSUE TITLE
Togglable timings 

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaMolSim/DFTK.jl#293]
If I understand correctly 
https://github.com/MasonProtter/ToggleableAsserts.jl/blob/master/src/ToggleableAsserts.jl
should make it possible to toggle timings on and off.

**Comment by mfherbst** [comment]
Yes that's actually pretty much what we do right now anyway. Probably one should make it into a ToggableTimer package. Regarding the package, it definitely superseeds https://github.com/JuliaMolSim/DFTK.jl/blob/master/src/common/asserting.jl though

**Comment by antoine-levitt** [comment]
Question is if we can make it toggleable at runtime

**Comment by mfherbst** [comment]
Theoretically yes, but since the original idea was to not pollute the stacktrace in case it is disabled then no (unless you want to compile each function twice, with and without timings)

**Comment by antoine-levitt** [comment]
Well that's what I mean. When assertions are turned off they just aren't there, so maybe we can do the same for timings. I need to think about it and try it out.

**Comment by mfherbst** [comment]
That's not fully true in the case of toggable assertions. [This line](https://github.com/MasonProtter/ToggleableAsserts.jl/blob/master/src/ToggleableAsserts.jl#L13) is always there even if assertions are turned off. The compiler will that probably remove it, but for timing it's not such a trivial statement, since it will be two functions on both sides of the `?`. I doubt it will be smart enough to completely remove that and that has consequences for inlining etc. So I'd be more careful there.

**Comment by mfherbst** [comment]
Can now be done with preferences or by calling `DFTK.set_timer_enabled!(false)`.
