### ISSUE TITLE
Thoughts on a New Package

### ISSUE THREAD

**Issue by umbriquse** [JuliaMolSim/DFTK.jl#373]
@antoine-levitt @mfherbst 
I've been developing a package that utilizes DFTK in order to quickly create systems to test for physical characteristics. I was curious if you would like to merge these higher order functions or if it would be more appropriate to create a separate package?

The below function uses the created PlaneWaveBasis and self_consistent_field key words along with other arguments to optimize the geometry of the given lattice and finding the relaxed state of the system.
```
function optimizeLatticeParameters(oldBasis::PlaneWaveBasis; 
    fileLocation::String = datadir("sim") * ".bson", 
    freeAtoms = oldBasis.model.atoms, 
    optimizeAtoms::Bool = false, 
    optimizeLattice::Bool = false, 
    useConstraints::Bool = false, 
    kwargs...
    )::NamedTuple
```

NOTE: My work may develop into using your package in calculating the molecular dynamics of the given system.

**Comment by mfherbst** [comment]
Cool! Great to hear you are developing a package using DFTK :smile:.

I think whether this sort of stuff should live in DFTK depends a bit on the scope you have in mind. I think some aspects you mentioned (like optimising the structure) could very well live in DFTK especially since I would expect the coupling between SCF and optimiser to be rather strong (and with Optim or similar it's not that much code you need). Other aspects, however, like setting up complex simulation workflows I feel are outside our intended scope. Also one aspect to keep in mind is that Julia packages tend to be rather narrow in scope and instead glance with flexible interfaces to interact with each other. DFTK I see more as the package for core electronic structure theory.
But I'm curious: Could you be more specific what you want to focus on: Workflow? Methods on top of DFTK? Management of results?

Also: One of the things that has been bugging me for a while is that Julia does not have a standardised way to specify chemical systems. Recently a few packages have emerged to deal with modelling molecules or solids and it would be good to come up with something like a light-weight ASE that just defines a nice way to transfer data between packages. I haven't quite had the time to think about this properly, but I suppose working towards that could also benefit what you have in mind?

**Comment by antoine-levitt** [comment]
Our explicit purpose with DFTK was to avoid a "everything and the kitchen sink" package where eg the MD module would be very coupled with the DFT solver. See eg https://juliamolsim.github.io/DFTK.jl/dev/examples/geometry_optimization/ for an example of this: there's only a few lines of glue code.

So I guess it depends on specifics: if you need more than a few lines of code to interface with DFTK or need something very internal to DFTK, then it means that DFTK is missing a feature and that functionality should ideally live in DFTK (see eg the `external/` folder where we have interfaces to various external codes) . Otherwise, if you need just energies and forces, DFTK has done its job and any further code should live outside it, and preferably should even see DFTK as a (switchable) backend. I think ASE is designed from that point of view?

**Comment by antoine-levitt** [comment]
PS: if you want to relax the lattice parameters, you need stresses. We haven't implemented it yet as 1) it's pretty annoying to do 2) we're hoping forward AD helps us there but haven't had time to investigate properly.

**Comment by mfherbst** [comment]
>  I think ASE is designed from that point of view?

Yes indeed. The idea is you just plug in an interface to compute energies, forces, stresses etc and drive whatever follows from that.

**Comment by umbriquse** [comment]
The scope of the package I am creating is intentionally vague. It has potential for many capabilities regarding molecular dynamics, system relaxation, and lattice optimization (imagine something akin to Abinit). The immediate aim of this package is to be able to model the interactions between molten basalt and metallic/ceramic surfaces.

I understand the reasoning behind keeping the scope of DFTK small and specialized, and agree with that philosophy. It makes DFTK a lot more of a universal package used for solving the DFT problems. I like the idea of using DFTK as a backend for the scf calculations in the package I am creating, but I do think that there would be some chances for merging. 

Some ideas for functions I think would be useful for the DFTK package would be convenience functions for setting up systems pre-SCF calculation. Some of these functions may include: quickly create a solid, gas molecules, or liquid, determine the minimum number of kPoints, and Ecut that is needed for the energy to converge to a given tolerance, and choose the most appropriate scf-solver based upon the given system. This list is not exhaustive, and some functions may not even be feasible (just some ideas I would like to attempt). I'm curious what your thoughts are on these types of functions, and if you are interested in using these functions in DFTK.

**Comment by umbriquse** [comment]
Also, the way i optimize the lattice parameters is, using optim, to adjust the lattice by a scalar that minimizes the systems energy. I figure that should be pretty close to the true lattice configuration.

**Comment by antoine-levitt** [comment]
> Some ideas for functions I think would be useful for the DFTK package would be convenience functions for setting up systems pre-SCF calculation. Some of these functions may include: quickly create a solid, gas molecules, or liquid, determine the minimum number of kPoints, and Ecut that is needed for the energy to converge to a given tolerance, and choose the most appropriate scf-solver based upon the given system

Some of these are a good fit for DFTK, some less. Creating solids, molecules or liquid should be done eg by ASE. Convergence and solver determination does belong to DFTK and we are actively thinking in that direction, from the point of view of numerical analysis.

> Also, the way i optimize the lattice parameters is, using optim, to adjust the lattice by a scalar that minimizes the systems energy. I figure that should be pretty close to the true lattice configuration.

That's sufficient for simple lattices (eg BCC FCC). For more general lattices where you need to relax many parameters, you probably want gradient information, ie stresses.

**Comment by mfherbst** [comment]
All right I see, thanks for the details @umbriquse. I think the rough line of division is that everything to do with choosing the physics (setting up the system, appropriate DFT model, etc.) goes beyond DFTK, but once you have settled on this choosing the numerics to solve the resulting problem (SCF solver, algorithms, convergence tolerances, ...) belongs here.

That said we are currently actively working on methods that take the burden of choosing computational parameters away from users as much as possible (using arguments based on numerical analysis and physics). For an example see our recent work on [LDOS mixing](https://arxiv.org/abs/2009.01665) to get an idea on the spirit that currently drives us. Clearly there is still much left to improve upon our current state, so anything that goes in such a direction we would more than welcome here :smile:.

**Comment by mfherbst** [comment]
This discussion seems to have reached an end. Feel free to reopen @umbriquse if you feel there is more you want to add to this.

**Comment by umbriquse** [comment]
There are plans to review this and work on this more, but at a later time.
