### ISSUE TITLE
Timing of threaded parts

### ISSUE THREAD

**Issue by jaemolihm** [JuliaMolSim/DFTK.jl#395]
Hi,

If I understand correctly, currently `DFTK.timer` cannot time functions called inside threaded regions because `TimerOutputs` is not thread-safe.

I've came up with the following (potential) solution (see `macro timing`):

```Julia
using TimerOutputs
using Base.Threads
using LinearAlgebra
BLAS.set_num_threads(1)

"""TimerOutput object used to store timings."""
const timer = TimerOutput()

"""
Shortened version of the `@timeit` macro from `TimerOutputs`,
which writes to the timer.
"""
macro timing2(args...)
    TimerOutputs.timer_expr(__module__, false, :($timer), args...)
end
"""
If threadid() == 1, call the timer.
Otherwise, do not call the timer.
"""
macro timing(args...)
    esc(quote
        if threadid() == 1
            @timing2($(args...))
        else
            esc($(last(args)))
        end
    end)
end

const arr = rand(1000, 1000, 3)

function run_serial()
    for i in 1:3
        @timing "serial" begin
            println("call eigvals, i=$i, thread $(threadid())")
            e = eigvals(arr[:, :, i])
        end
    end
end
function run_threads()
    @threads for i in 1:3
        @timing "threads" begin
            println("call eigvals, i=$i, thread $(threadid())")
            e = eigvals(arr[:, :, i])
        end
    end
end

reset_timer!(timer)
@time run_serial()
@time run_threads()
print_timer(timer)
```

The output is as follows. The timer in the `run_threads` function is called only once, by Thread 1.
Since only the first thread measures the timing, the timing will be inaccurate if the load is not balanced.

```
call eigvals, i=1, thread 1
call eigvals, i=2, thread 1
call eigvals, i=3, thread 1
  2.343138 seconds (96 allocations: 46.698 MiB, 3.03% gc time)
call eigvals, i=1, thread 1
call eigvals, i=2, thread 2
call eigvals, i=3, thread 3
  0.993834 seconds (68.65 k allocations: 50.199 MiB)
 ──────────────────────────────────────────────────────────────────
                           Time                   Allocations      
                   ──────────────────────   ───────────────────────
 Tot / % measured:      4.83s / 63.4%            230MiB / 40.6%    

 Section   ncalls     time   %tot     avg     alloc   %tot      avg
 ──────────────────────────────────────────────────────────────────
 serial         3    2.34s  76.4%   781ms   46.7MiB  50.0%  15.6MiB
 threads        1    724ms  23.6%   724ms   46.7MiB  50.0%  46.7MiB
 ──────────────────────────────────────────────────────────────────
```

The macro was motivated by https://discourse.julialang.org/t/macro-for-optional-threading-not-working/40491/2.

Do you think this solution works? Is there any problem that I overlooked?
(I have to admit, I do not fully understand how Julia macro-and this code-works...)

P.S.
After doing this, I saw your comment in https://github.com/KristofferC/TimerOutputs.jl/issues/72#issuecomment-720681410. Is this what you intended there?

P.P.S.
I am developing a Julia program for Wannier-function-based tight-binding model calculations with a hybrid MPI-Julia Threads parallelization. I've referred to `DFTK.jl` a lot (especially the codes in `common/`); it is really helpful in designing and developing my code.
Thanks a lot for this nice package!

**Comment by mfherbst** [comment]
Hi @jaemolihm

thanks for getting in touch and for your nice words about DFTK. I'm happy to hear you find it useful!

I have not run your code, but on first glance I'd say that this looks reasonable. I think it has a few drawbacks, but I'm not entirely sure if and how they can be avoided. Timing threaded code is just generally tricky.

What you mention first is the aspect of the balanced load: That we are definitely not doing very well in DFTK as of now and so that is something to always keep in mind when interpreting the timings. Additionally I see the following issues: (1) Your macro introduces extra entries in the stack traces due to the `if`-statement. That's a general issue with timings (we have it with the current setup as well) and I'm not sure if that can be avoided. That can be a bit annoying for debugging. (2) I wonder if the compiler is clever enough to remove all the dead code you introduce with the `if`. The problem I see is that the `threadid` can only be resolved at runtime and therefore each time you use this macro you essentially double the compiled code (one instance with threading and one without). This can mess with execution prefetching, might noticably increase precompilation times and worst of all might prevent inlining. Thus it might have a noticeable negative impact on performance. Before including this inside the performance-critical threaded regions in DFTK (like the `G_to_r!), where timings are currently disabled by default, it would therefore need to be very thoroughly tested for such implicit performance penalties.

Also I don't think the right spot to contribute this code is DFTK. Have you thought about contributing your modifications to TimerOutputs directly?

**Comment by jaemolihm** [comment]
Thanks a lot for the comments!
I had overlooked the problem of stack traces and dead codes. This change should definitely be throughly tested before it is included somewhere.
I agree that this kind of change should be targetted to TimerOutputs.jl. I will consider contributing there, after I resolve the issues you mentioned.
Thank you again for the discussion. This issue can be closed.

**Comment by antoine-levitt** [comment]
Hi, just replying to
> I am developing a Julia program for Wannier-function-based tight-binding model calculations with a hybrid MPI-Julia Threads parallelization. I've referred to DFTK.jl a lot (especially the codes in common/); it is really helpful in designing and developing my code.

glad you liked it! There's an open PR on wannier stuff (and some more code that should be integrated with DFTK at some point) if you find it useful.
