### ISSUE TITLE
memory usage vs threading

### ISSUE THREAD

**Issue by bhalonen** [JuliaMolSim/DFTK.jl#409]
We are currently running jobs with 4 Julia threads, 4 BLAS threads, and one FFTW thread. The current simulation is using about 71G of memory, is there any way to up the thread usage or should we be targeting smaller simulations?

**Comment by mfherbst** [comment]
I'm not sure how bottlenecked you are for memory, but in case you can afford it, try the experimental MPI parallelisation. [It scales a lot better](https://juliamolsim.github.io/DFTK.jl/stable/guide/parallelization/#Options-for-parallelization) even for like 4-8 CPUs. It has a slightly bigger memory overhead (since some things are redundant between processes), but if you are lucky you might manage. In either case you will have a much better use of your CPUs using MPI, such that 4 MPI threads, that fit in RAM might still be the more economical approach than what you're doing now.

If you could make some rough notes on the RAM overhead of MPI, I'd be interested, actually.

**Comment by antoine-levitt** [comment]
We haven't been super careful to minimize RAM footprint. That said, 

1. RAM usage is notoriously hard to measure accurately, and a high %MEM in top does not always mean a high real RAM usage. This is especially true when using threads
2. julia is as far as I know not particularly eager to release memory unless needed
3. standard DFT should not really be RAM-limited: if it doesn't fit in RAM, it probably doesn't compute in a real time frame
4. depending on what you're doing, you might be hitting a function we haven't been bothered to optimize because it hasn't come up in our work. If you can post a self-contained input script we can take a look.

MPI is indeed better scaling if you have kpoints. The RAM overhead should hopefully be small for "typical" problems (ie truly periodic systems without a huge chunk of vacuum)

**Comment by mfherbst** [comment]
Ah actually now that Antoine mentions Vacuum. There is the option to "disable" XC functionals on vacuum using a cutoff density, which could help quite a bit if you have loads of vacuum (like half the cell).

**Comment by umbriquse** [comment]
@mfherbst For clarification, by density you mean electron density no?

**Comment by mfherbst** [comment]
> you mean electron density no?

Yes.

> Would a density cutoff of 0.01% of the maximum electron density seem reasonable?

Oh I would be very careful there. Some of the density components can get very small. On the caffeine example shown on our Threading documentation I used for example:
```julia
xc = Xc(:gga_x_pbe, :gga_c_pbe, density_threshold=1e-16)
```
going smaller than that could introduce quite a big error in your results, but just try it.

**Comment by mfherbst** [comment]
Closing this usage discussion for now. Feel free to reopen if not all points have been clarified.
