### ISSUE TITLE
Magnetic fields in Package features.

### ISSUE THREAD

**Issue by Lijieying** [JuliaMolSim/DFTK.jl#544]
What does the magnetic fields implicate in package features, listed on the webpage [https://juliamolsim.github.io/DFTK.jl/stable/]?   A means of adding an external magnetic filed to a system, or a calculated property of a system ? Sorry to that I have not found a paper on the webpage about the magnetic fileds yet.  I would appreciate If you can give me a link of that paper.

thanks
jyli

**Comment by antoine-levitt** [comment]
Hi,

We support finite magnetic fields (there's a tutorial for that). We don't have magnetic response properties (the basic infrastructure of response is there but it's not hooked up to properties yet)

**Comment by mfherbst** [comment]
The example @antoine-levitt refers to is https://juliamolsim.github.io/DFTK.jl/stable/examples/gross_pitaevskii_2D/ where an external magnetic field is added.

Otherwise we currently support "basic" magnetic properties like total magnetisation, see https://juliamolsim.github.io/DFTK.jl/stable/examples/collinear_magnetism/

**Comment by Lijieying** [comment]
Thanks, It's very useful.

**Comment by mfherbst** [comment]
I'm closing this for now since your question seems answered. Feel free to reopen @Lijieying if you have more questions.
