### ISSUE TITLE
Non-linear core correction

### ISSUE THREAD

**Issue by azadoks** [JuliaMolSim/DFTK.jl#759]
Now that basic norm-conserving UPF support is implemented, the next step should be to implement NLCC; without it, there are very few pseudos we can actually use.

I'm a bit ignorant about what needs to be done to make this happen other than to adjust the exchange-correlation term to include the core charge density from the pseudopotential.

It would be good to discuss here what needs to be done both in theory and with practical considerations for how the data should be passed around in the code.

**Comment by antoine-levitt** [comment]
> I'm a bit ignorant about what needs to be done to make this happen other than to adjust the exchange-correlation term to include the core charge density from the pseudopotential.

I think basically this? I'd have to look at the papers (I'm interested if you have good references), but basically, instead of computing the XC energy of rho (the valence pseudodensity), you compute the XC energy of rho+rho_at, rho_at being the core density? If that's just what it is, then the rho_at needs to be passed to the xc. Right now there's nothing in the xc that interacts with the pseudos, but xc does have access to the full basis, so we just have to expose nonlinear_core_correction_fourier(el::Element, q), and then xc.jl constructs the core density (form factor from nonlinear_core_correction, plus structure factors as usual) in its constructor and adds it just before calling xc. Possibly the forces also have to be adapted, following what's done in local.jl

**Comment by mfherbst** [comment]
That about summarises my knowledge and understanding as well.

Since we have a data structure to compute various derivatives of the density and store it in the xc.jl, you only have to make sure to add `rho_at` beforehand and that should largely be it.

**Comment by azadoks** [comment]
Ok, but then if we aren't moving the atoms this should be calculated once and stored somewhere, no?

**Comment by mfherbst** [comment]
There is no need to move anything. You can access the atoms from the XC term and compute and store the NLCC atomic density there or not?

**Comment by azadoks** [comment]
"Moving the atoms" was probably not the right way to say this (I was thinking of geometry optimization). It also doesn't make a lot of sense because geometry optimization isn't done in DFTK.

But yes, it does make sense to calculate and store the NLCC charge density in the XC term when it's created.

**Comment by azadoks** [comment]
I think we could get guess charge density from the pseudo and NLCC done together in one shot by:

- Adding a `numeric_superposition` function to `guess_density.jl`
  - This should probably implement the same form-factor optimization as in the local and nonlocal terms
- Adding a `eval_psp_rho_valence_fourier` function to `NormConservingPsp` (PP_RHO)
- Adding a `eval_psp_rho_core_fourier` function to `NormConservingPsp` (PP_NLCC)
- Add the corresponding functions to `ElementPsp`
- Call `numeric_superposition` with a flag for valence charge to get the guess density
- Call `numeric_superposition` with a flag for core charge to get the NLCC charge in `XcTerm`

Thoughts?

**Comment by antoine-levitt** [comment]
Yes there's a nice factorization opportunity we haven't exploited. Rather than superposition I'd factor it out to a `translate(basis, f, shift)` (as well as in place versions of we need the speed, possibly with alpha/beta versions as in mul!) that could then be called in the other functions (which do the accumulation themselves)

**Comment by azadoks** [comment]
While it sounds cool, it also sounds like a good amount of work to understand and implement.
For the moment, I'd just like to get something working so that 90% of the PseudoDojo isn't unusable.

Draft PR: #766

**Comment by antoine-levitt** [comment]
Oh no I was just thinking out loud about simplifying the code a bit to hide the "low-level" details of structure factors into general-purpose translation functions, based on what you said about numeric_superposition. Great work, don't let me slow you down, I'll refactor when I have the time!

**Comment by antoine-levitt** [comment]
Closing as this is done (right?)
